manage_my_process

diff --git a/processes_and_signals/manage_my_process b/processes_and_signals/manage_my_process
--- a/processes_and_signals/manage_my_process
+++ b/processes_and_signals/manage_my_process
@@ -1,8 +1,36 @@
-#!/usr/bin/env bash                                
-# display all running PID                          
-                                                  
-while :                                            
-do                                                 
-        echo "I am alive!" >> /tmp/my_process      
-        sleep 2                                    
-done
+#!/bin/bash
+
+case "$1" in
+    "start")
+        if [ -f "/var/run/my_process.pid" ]; then
+            echo "Error: manage_my_process is already running."
+        else
+            echo "I am alive!" > /tmp/my_process &
+            echo $! > /var/run/my_process.pid
+            echo "manage_my_process started"
+        fi
+        ;;
+    "stop")
+        if [ -f "/var/run/my_process.pid" ]; then
+            kill -9 $(cat /var/run/my_process.pid)
+            rm /var/run/my_process.pid
+            echo "manage_my_process stopped"
+        else
+            echo "Error: manage_my_process is not running."
+        fi
+        ;;
+    "restart")
+        if [ -f "/var/run/my_process.pid" ]; then
+            kill -9 $(cat /var/run/my_process.pid)
+            rm /var/run/my_process.pid
+            echo "manage_my_process stopped"
+        fi
+        echo "I am alive!" > /tmp/my_process &
+        echo $! > /var/run/my_process.pid
+        echo "manage_my_process restarted"
+        ;;
+    *)
+        echo "Usage: manage_my_process {start|stop|restart}"
+        exit 1
+        ;;
+esac
